# Generated by Django 5.0 on 2025-08-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customer_date_staff_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='unpaid_leave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Unpaid Leave(Days)'),
        ),
    ]
