# Generated by Django 5.0 on 2025-09-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_salaryrecord_unpaid_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='esi_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter ESI percentage (e.g. 1.75 for 1.75%)', max_digits=5, null=True, verbose_name='ESI (%)'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='pf_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter PF percentage (e.g. 12 for 12%)', max_digits=5, null=True, verbose_name='PF (%)'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='esi',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='ESI Amount'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='pf',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='PF Amount'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='unpaid_leave',
            field=models.IntegerField(default=0, verbose_name='Unpaid Leave(Days)'),
        ),
    ]
