# Generated by Django 5.0 on 2025-09-11 04:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_salaryrecord_esi_percent_salaryrecord_pf_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_quantity', models.PositiveIntegerField(default=0, help_text='Reorder level')),
            ],
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='esi_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter ESI percentage (optional, e.g. 1.75 for 1.75%)', max_digits=5, null=True, verbose_name='ESI (%)'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='pf_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter PF percentage (optional, e.g. 12 for 12%)', max_digits=5, null=True, verbose_name='PF (%)'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='staff',
            field=models.ForeignKey(help_text='Select a staff member', on_delete=django.db.models.deletion.CASCADE, to='core.staff'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='unpaid_leave',
            field=models.IntegerField(default=0, verbose_name='Unpaid Leave (Days)'),
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockins', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('sale', 'Sale'), ('service', 'Service Use'), ('wastage', 'Wastage'), ('other', 'Other')], default='sale', max_length=100)),
                ('bill_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.billitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockouts', to='core.product')),
            ],
        ),
    ]
