# Generated by Django 5.0 on 2025-09-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_alter_salaryrecord_esi_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='month',
            field=models.IntegerField(default=9, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Year'),
        ),
    ]
