# Generated by Django 5.0 on 2025-09-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_phoneotp_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
